---
- name: Update pulsys user keys
  hosts: all
  remote_user: pulsys
  become: true
  vars_files:
    - ../group_vars/all/main.yml
  vars_files:
    - ../group_vars/all/main.yml

  tasks:
  # to remove someone's keys from our servers:
  # remove their keys from the `pulsys_ssh_users` variable
  # then run this playbook again
    - name: get key content from github
      ansible.builtin.command: 'curl {{ item }}'
      loop: "{{ pulsys_user_github_keys }}"
      register: pulsys_user_keys_from_github
      changed_when: false

    - name: build authorized keys file
      ansible.builtin.template:
        src: templates/authorized_keys.j2
        dest: /home/pulsys/.ssh/authorized_keys
        group: pulsys
        owner: pulsys
        mode: '0600'
        backup: true

    - name: Update apt
      ansible.builtin.apt:
        force_apt_get: true
        cache_valid_time: 3600

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: true

