---
- name: "{{ configure_task_name }}"
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"
  when: ansible_os_family in ['Debian', 'RedHat']

- name: "{{ configure_task_name }}"
  ansible.builtin.include_tasks: windows.yml
  when: ansible_os_family == "Windows"
