
source "virtualbox-iso" "autogenerated_1" {
  boot_command             = ["<esc><wait>", "install <wait>", " auto=true", " priority=critical", " preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg <wait>", "<enter><wait>"]
  boot_wait                = "10s"
  disk_size                = "30480"
  guest_additions_path     = "/home/vagrant/VBoxGuestAdditions.iso"
  guest_os_type            = "Ubuntu_64"
  hard_drive_interface     = "sata"
  hard_drive_nonrotational = "true"
  http_directory           = "http"
  iso_checksum             = "sha256:10f19c5b2b8d6db711582e0e27f5116296c34fe4b313ba45f9b201a5007056cb"
  iso_url                  = "https://releases.ubuntu.com/22.04/ubuntu-22.04.1-live-server-amd64.iso"
  output_directory         = "output-virtualbox-iso-ubuntu22base"
  sata_port_count          = "5"
  shutdown_command         = "echo 'packer' | sudo -S shutdown -P now"
  ssh_agent_auth           = true
  ssh_username             = "pulsys"
  ssh_wait_timeout         = "6000s"
  vboxmanage               = [["modifyvm", "{{ .Name }}", "--memory", "8192"], ["modifyvm", "{{ .Name }}", "--cpus", "2"]]
  vm_name                  = "ubuntu22base"
}

build {
  sources = ["source.virtualbox-iso.autogenerated_1"]

  provisioner "ansible" {
    extra_arguments = [
      "--extra-vars",
      "ansible_python_interpreter=~/.asdf/shims/python"
    ]
    playbook_file = file("../ansible/vagrant-ubuntu-22-guest-additions.yml")
    user          = "pulsys"
  }

  post-processor "vagrant" {
    keep_input_artifact = false
    output              = "pulimage"
  }
}
