---
- hosts: all
  remote_user: pulsys
  become: true
  tasks:
    - name: add user keys
      authorized_key:
        user: pulsys
        state: present
        key: "{{ item }}"
      loop:
        - https://github.com/acozine.keys
        - https://github.com/bess.keys
        - https://github.com/beck-davis.keys
        - https://github.com/carolyncole.keys
        - https://github.com/christinach.keys
        - https://github.com/cwulfman.keys
        - https://github.com/dphillips-39.keys
        - https://github.com/eliotjordan.keys
        - https://github.com/escowles.keys
        - https://github.com/hackartisan.keys
        - https://github.com/hectorcorrea.keys
        - https://github.com/ishasinha1.keys
        - https://github.com/jaymeeh.keys
        - https://github.com/jkazmier-PUL.keys
        - https://github.com/jrgriffiniii.keys
        - https://github.com/kayiwa.keys
        - https://github.com/kelynch.keys
        - https://github.com/kevinreiss.keys
        - https://github.com/leefaisonr.keys
        - https://github.com/maxkadel.keys
        - https://github.com/mzelesky.keys
        - https://github.com/pdiskin.keys
        - https://github.com/regineheberlein.keys
        - https://github.com/rladdusaw.keys
        - https://github.com/sandbergja.keys
        - https://github.com/sdellis.keys
        - https://github.com/seanwarren77.keys
        - https://github.com/tpendragon.keys
        - https://github.com/rlskoeser.keys
        - https://github.com/VickieKarasic.keys
        - https://github.com/vh8154.keys
        - https://github.com/winsice-ng.keys
