---
- hosts: all
  remote_user: pulsys
  become: true
  tasks:
    - name: install globus deb file
      ansible.builtin.apt:
        deb: https://downloads.globus.org/globus-connect-server/stable/installers/repo/deb/globus-repo_latest_all.deb

    - name: install globus repo key
      ansible.builtin.apt_key:
        file: /usr/share/globus-repo/RPM-GPG-KEY-Globus
        state: present

    - name: install globus-connect server
      ansible.builtin.apt:
        name: globus-connect-server54
        state: present
        update_cache: true
