---
- hosts: all
  remote_user: pulsys
  become: true
  tasks:
    - name: add user keys
      authorized_key:
        user: pulsys
        state: present
        key: "{{ item }}"
      loop:
        - https://github.com/eliotjordan.keys
        - https://github.com/kevinreiss.keys
        - https://github.com/tpendragon.keys
        - https://github.com/escowles.keys
        - https://github.com/sdellis.keys
        - https://github.com/hackartisan.keys
        - https://github.com/jrgriffiniii.keys
        - https://github.com/christinach.keys
        - https://github.com/pmgreen.keys
        - https://github.com/cwulfman.keys
        - https://github.com/mzelesky.keys
        - https://github.com/carolyncole.keys
        - https://github.com/pdiskin.keys
        - https://github.com/kelynch.keys
        - https://github.com/hectorcorrea.keys
        - https://github.com/rlskoeser.keys
        - https://github.com/bess.keys
        - https://github.com/sandbergja.keys
        - https://github.com/maxkadel.keys
